# Generated by Django 5.0.1 on 2024-02-15 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_e_mail_user_phone_number_alter_user_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Customer',
        ),
    ]
